apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment-1
  namespace: test-namespace-1
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: test-deployment-1
  template:
    metadata:
      labels:
        name: test-deployment-1
    spec:
      containers:
      - image: fedora:latest
        command: [ "sleep", "600" ]
        name: test-container
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment-2
  namespace: test-namespace-2
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: test-deployment-2
  template:
    metadata:
      labels:
        name: test-deployment-2
    spec:
      containers:
      - image: fedora:latest
        command: [ "sleep", "600" ]
        name: test-container
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment-3
  namespace: test-namespace-3
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: test-deployment-3
  template:
    metadata:
      labels:
        name: test-deployment-3
    spec:
      containers:
      - image: fedora:latest
        command: [ "sleep", "600" ]
        name: test-container
        imagePullPolicy: Always


